FROM golang:1.14-stretch

WORKDIR /go-bank-transfer

COPY . .

RUN go mod download
RUN go get github.com/cespare/reflex

COPY script/reflex/reflex.conf /

EXPOSE 3001

ENTRYPOINT ["reflex", "-c", "./script/reflex/reflex.conf"]